# Numpy is the fundamental package for scientific computing in python.
# It is  a python library that provides  a multidimension array  object, various
# derived objects( such as masked arrays and matrics), and an assortment of routines for fast operations on arrays, including mathematicals, logical, shape manipulation , sorting, selecting , I/O , discrete Fourier transforms, basics liner algebra, basic statistical operations, random simulation and much more.

# At the core of the Numpy package, is the ndarray object. This encapsulates 
# n- dimesional arrays of homogeneous data  types.

In [2]:
# Numpy arrays vs Python Sequences(sequences is just a  lists, sets )

# Numpy arrays have a fixed size at creation, unlike Python lists( Which can grow dynamically). Changing the size of an
# ndarray will create  a new array and delete the original.

# The elements in a Numpy array are all required to be the same data type, and thus will be the same size in memory 
# Numpy arrays facilites advanced mathematical and other types of operation on large numbers of data. Typically, such
# operations are executed more efficiently and with less code than is possible using Python's Built-in sequences.

# A growing plethora of scientific and mathematical Python- based packages are using Numpy arrays; though these typically 
# support Python-sequence input , they convert such input to Numpy arrays prior to processing, and they often output Numpy
#arrays

# How to create Numpy Arrays

In [1]:
# importing Numpy 

import numpy as np

a = np.array([1,2,3])

print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
# 2D and 3D numpy

b = np.array([[1,2,3],[4,5,6]])

print(b)


[[1 2 3]
 [4 5 6]]


In [5]:
# 3D

c = np.array([[[1,2],[3,4],[5,6],[7,8]]])

print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [6]:
# how to convert data type 

# lets create integer to float

np.array([1,2,3,4], dtype=float)

array([1., 2., 3., 4.])

In [7]:
# lets create data type to boolean

np.array([1,2,3,4], dtype= bool)

# in Python non 0 value is consider as True

array([ True,  True,  True,  True])

In [8]:
# lets create data type to complex

np.array([1,2,3,4], dtype= complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [9]:
# np.arange

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [10]:
# with reshape 
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
# np.ones and np.zeros

np.ones((3,5))

# why we use  np.ones and np.zeros because where every we need intialization we use ones and zeros

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# how to use array Attributes

In [12]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [13]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
# ndim ( Number of dimension)
 
a1.ndim



# what ndim do? it tells what is demension of the array
# in this example tu dekh sakta hai ki 1 dimesion hai


1

In [16]:
a2.ndim

2

In [18]:
# shape
print(a3.shape)

(2, 2, 2)


In [19]:
# size

a1.size

10

In [20]:
a2.size

12

In [21]:
a3.size

8

In [22]:
#itemsize tell ( har iteam memory may kitana size le raha hai)

a1.itemsize

# ye bol raha hai ki 4 bites ki memory use hua hai

4

In [23]:
a2.itemsize

8

In [24]:
a3.itemsize

4

In [26]:
# int32 4 bites leta hai memory and int64 8 bites leta hai memory

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# changing datatype

In [29]:
#astype
a3.astype(np.int64) # or you can do viceversa int34 remember int32 take less memory and int64 takes more

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

# Array operation

In [38]:
b1 = np.arange(12).reshape(3,4)
b2 = np.arange(12,24).reshape(3,4)




In [39]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
# scalar operation 

# Arithmetic 

print(b1*2)  # Ye har element pay jayega aur 2 se multiple karega"
#  ismay koi bhi operation kar sakte hai *,/,+,_"

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [55]:
# vector operation 

# arithmetic

print(b1*b2) # ismay ak array dusare array se operate hota hai, aur ismay koi bhi operation kar sakte hai


[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


 # Array functions

In [56]:
c1 = np.random.random((3,3))

c1 = np.round(c1*100)

c1

array([[75., 29., 54.],
       [75., 49., 49.],
       [12., 42., 12.]])

In [57]:
# min,max,product

np.max(c1) # koi bhi function use kar sakte hai

75.0

In [58]:
# min, max, product

# abhi ye upar pure array ka min max and product de raha hai but agar kisko 
# ak pure row ka karna hai tho kaise karenge aur agar ak column ka karna hai tho kaise kareneg

# ismay 0 --> column hota hai and 1 --> row hota hai

np.min(c1, axis=0)


array([12., 29., 12.])

In [59]:
# row ka max

np.max(c1, axis=1)



array([75., 75., 42.])

In [60]:
# mean, meadian, std

np.mean(c1)

44.111111111111114

In [61]:
# aur agar single column wise karna hai tho axis= 0 karna hai and for row axis= 1

np.mean(c1,axis=0)

array([54.        , 40.        , 38.33333333])

# Indexing and slicing


In [64]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [65]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
# agar koi bole ke last wala item nikalan hai a1 ka tho kaise hoga
# simple hai

a1[-1] # a1 ka last item 9 hai aur output ayaa 9

9

In [67]:
a2 # abhi may 6 nikal na hai tho kaise

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
a2[1,2] # tho ismay  first hum row ka number denge aur hamesh 0 se start hota hai tho ismay
        # 1 row may arah hai and column wise 2 may

6

In [69]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [70]:
# abhi ismay 5 value nikalna hai
# tho hamesha socho ki 3D banta kaise hai, tho 3D banta hai 2D se 

a3[1,0,1]

5

In [71]:
# chalo ismay hum 3 nikalte hai 

a3[0,1,1]

3

In [72]:
# chalo 0 nikalte hai

a3[0,0,0]

0

# Abhi tak hum indexing kar rahe the

# but hum slicing ke help se multiple item ko fetch kar sakte hai

In [73]:
# ye slicing hai

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
a1[2:5]

array([2, 3, 4])

In [75]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
# lets say imay nikal na hai first row

a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [78]:
# chalo sab cone vala value chaiya 0,3,8,11

a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [80]:
# chalo nikalte hai 1,3,9,11

a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [81]:
a2 # just 4 aur 7 chaiye

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
a2[1:2,::3]

array([[4, 7]])

In [87]:
# chalo nikalte hai 1,2,3,5,6,7

a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [90]:
# chalo ddekhate hai 3D ke case may kaise karte hai

a3= np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [92]:
# chalo koi bole ye nikalna hai [[ 9, 10, 11],
                               # [12, 13, 14],
                                #[15, 16, 17]],
        

a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [93]:
# lets pick [[[ 0,  1,  2],
            #[ 3,  4,  5],
            #[ 6,  7,  8]],
        
        
        
            #[[18, 19, 20],
            #[21, 22, 23],
            #[24, 25, 26]]])
            
a3[::2]
        

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [94]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [96]:
# ismay 3,4,5

a3[0,1]

array([3, 4, 5])

In [98]:
# lets print 10,13,16
a3[1,:,1]

array([10, 13, 16])

In [99]:
#lets print 22,23,25,26

a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [100]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [104]:
# 0,2
#18,20

a3[::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

# iteration ( that means you can run loops on arrays)

In [7]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

In [8]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [16]:
a1

for i in a1:
    print(i)# ye kya karega ki a1 ke shaare item print kare de dega
    

0
1
2
3
4
5
6
7
8
9


In [17]:
a2

for i in a2:
    print(i) # jab aap 2D pay loops chalate ho tho ak row ak baar print hota hai aur ak ak karke sab print hojayega

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [18]:
a3

for i in a3:
    print(i) # 3D may loop chalayenge tho ak baar may 2D print hota hai jaise 
             # [[0 1 2]
             # [3 4 5]
             # [6 7 8]]
                
                
            # dihre dihre sab print hoga

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [19]:
# agar har item ke upar loop chalana hai tho( dekho ouput kaisa araha hai 2D ye 3D may but humay idhar ak ak
# item print kar warna hai tho nditer bolke function hota hai wo use kar na hai, chalo 2D may use karte hai

for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [20]:
# aur same 3D may karte hai 

# ye nditer kaam kaise karta chalo dekhate hai, ye 2D,3D kitane bhi D ho usko 1D may lata hai aur print karta hai

for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [22]:
# Transpose

a2  # abhi a2 may 3,4 hai Transpose use kar ke aap 4,3 kar sakte ho

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [26]:
# aur isko T dalke bhi use kar sakte hai

a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [27]:
# ravel

# kya karta hai ye 2D,3D kisi bhi D ko 1D may convert kardeta hai

a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
# chalo abhi 3D may use karte hai 
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# stacking

In [29]:
# stacking kab use ataa hai jab humye 2 arrays ko join karna ho tab
# aur ye horzontal hota hai and vertical hota hai

# Horizontal

a4 = np.arange(4).reshape(2,2)
a5 = np.arange(5,9).reshape(2,2)
a4

array([[0, 1],
       [2, 3]])

In [30]:
a5

array([[5, 6],
       [7, 8]])

In [31]:
np.hstack((a4,a5))

array([[0, 1, 5, 6],
       [2, 3, 7, 8]])

In [32]:
# aise he aap kitana bhi join kar sakte ho horizontally 

np.hstack((a4,a5,a4)) #aise he kitana bhi join kar sakte hai

array([[0, 1, 5, 6, 0, 1],
       [2, 3, 7, 8, 2, 3]])

In [33]:
# Aise he vertical bhi join karsakte hai


np.vstack((a4,a5))

array([[0, 1],
       [2, 3],
       [5, 6],
       [7, 8]])

# yenha question ye ataa hai ki satcking use kyun karte hai kabhi aisa hota hai ki
# data multiple source se ataa hai jaise ki database, API, data scraping se aur 
# satcking may arrays ka shape same hona chaiye

# Splitting

In [34]:
# splitting is just the opposite of stacking
 # same there are 2 splitting horizontal and vertical
    


<img   src= "splitting.jpg" style = "width:400px;height:400px">

In [37]:
a4

array([[0, 1],
       [2, 3]])

In [35]:
np.hsplit(a4,2)

[array([[0],
        [2]]),
 array([[1],
        [3]])]

In [36]:
np.vsplit(a4,2)

[array([[0, 1]]), array([[2, 3]])]

# Advance Numpy

In [2]:
# speed test in list

a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)] 

c = []
import time

start = time.time()


for i in range(len(a)):
    c.append(a[i]+ b[i])
print(time.time()- start) # ye wala task karne may 2 seconds laga

    


4.4087607860565186


In [3]:
# same kaam in numpy may karte hai

import numpy as np

a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()

c = a+b # numpy may loops chalane ki jarurat nahi hota


print(time.time()- start)


0.23154425621032715


In [ ]:
# numpy c type ka array that mean static array jiska size badaa aur chota nahi hota

In [11]:
# memory , chalo memory dekhate hai ki kitana use hota hai

a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)



89095160

In [12]:
a = np.arange(10000000)

sys.getsizeof(a)

40000112

In [13]:
# EDI ke upar depend hai ki konsa int use karta hai Jupyter notebook int32 same google collab int64 use karta hai

# chalo isko int16 karte hai
a = np.arange(10000000,dtype = np.int16)

sys.getsizeof(a)

20000112

In [17]:
# same int8 karte hai

a = np.arange(10000000,dtype = np.int8)

sys.getsizeof(a)

10000112

# Advance indexing

In [18]:
# Normal Indexing and slicing

a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
# agar bolun 5 nikalna hai tho kaise  in normal indexing

a[1,2]

5

In [20]:
a[::2]

array([[0, 1, 2],
       [6, 7, 8]])

In [24]:
# fancing indexing ---- may bas ak list dena hota hai

# chalo ismay [ 0,  1,  2],
            # [ 9, 10, 11]])
    
a[[0,3]]

array([[ 0,  1,  2],
       [ 9, 10, 11]])

In [25]:
# aur agar column nikalna hai tho kaise 1,2 column

a[:,[1,2]]


array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [4]:
# Boolean Indexing

# Boolean Indexing may hum condition se number pull karte hai

In [5]:
import numpy as np

In [6]:
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[82, 52, 21, 65],
       [58, 33, 66, 97],
       [36, 38, 26, 80],
       [82, 33, 10, 11],
       [ 9, 40, 26, 77],
       [99, 25, 61, 24]])

In [8]:
# Fetch all numbers greater than 50
a>50     # ab ye condition har item may jake puchega ki kya aap 50 se big ho asie kar ke sab item check karega and boolean
         # value may output ayega
    
    # ye boolean mask ki taraha use kar sakte hai
    


array([[ True,  True, False,  True],
       [ True, False,  True,  True],
       [False, False, False,  True],
       [ True, False, False, False],
       [False, False, False,  True],
       [ True, False,  True, False]])

In [9]:
# abhi hum log kya karenge ki boolean wala array ko utaa ke original wale may daal denge isay false wala value nikal jayega
# and true wala value bachega

a[a>50]

array([82, 52, 65, 58, 66, 97, 80, 82, 77, 99, 61])

In [10]:
# find out even numbers 

a%2 == 0

array([[ True,  True, False, False],
       [ True, False,  True, False],
       [ True,  True,  True,  True],
       [ True, False,  True, False],
       [False,  True,  True, False],
       [False, False, False,  True]])

In [11]:
# phir humlog isko orignal array may daldete hai
a[a%2==0]

array([82, 52, 58, 66, 36, 38, 26, 80, 82, 10, 40, 26, 24])

In [16]:
# find all numbers greater than 50 and are even
(a >50)&(a%2 ==0)  # here we are using & instead of and find it out

array([[ True,  True, False, False],
       [ True, False,  True, False],
       [False, False, False,  True],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [17]:
a[(a >50)&(a%2 ==0)]

array([82, 52, 58, 66, 80, 82])

In [19]:
# find all numbers not divisible by 7

a[~(a % 7 ==0)]

array([82, 52, 65, 58, 33, 66, 97, 36, 38, 26, 80, 82, 33, 10, 11,  9, 40,
       26, 99, 25, 61, 24])

# Broadcasting

In [ ]:
# The term broadcasting describe how Numpy treats with different shapes during arithemetics operation.

# The smaller array is "broadcast" across the larger array so that they have compatible shapes.

In [20]:
# same shape

a= np.arange(6).reshape(2,3)
b= np.arange(6,12).reshape(2,3)
print(a)

print(b)
    


[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [22]:
c = a+b # same shape ka array tha tho hogaya add
c

array([[ 6,  8, 10],
       [12, 14, 16]])

In [26]:
# abhi question idhar ye ataa hai ki different type ka shape hoga tho kya add hoga

a= np.arange(6).reshape(2,3)
b= np.arange(3).reshape(1,3)

print(a)
print(b)

# chalo add karke dekhate hai different size ka add hota hai kya

d = a+b
d
# add hogaya

[[0 1 2]
 [3 4 5]]
[[0 1 2]]


array([[0, 2, 4],
       [3, 5, 7]])

# Broadcast rules 


In [ ]:
# 1. Make the two arrays have the same number of dimesions.
     # if the number of dimesions of the two arrays are different, add new dimension with size 1 to the head of the array
     # with the smaller dimension.
        
# 2. Make each dimension of the two arrays the same size.
    # if the size of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the 
    # other array.
    
    # if there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is 
    # raised.

<img src = "numpypics.jpg">

In [27]:
# lets solve a example 

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)



[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]


In [28]:
#lets add 

print(a+b)

# niche iska explation hai hamesh yaad rahe ki agaar 1 hoga tho he broadcasting perform hota hai

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


<img src = "1d2d.jpg">

In [29]:
a = np.arange(12).reshape(3,4)
b= np.arange(3)

print(a+b)

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

<img src = "broadcastingaa.jpg" style = "width:500px;height:500px">